### ISSUE TITLE
Make Pluto dependency optional?

### ISSUE THREAD

**Issue by frankier** [JuliaDocs/DemoCards.jl#130]
Would it be possible to make the Pluto dependency optional? Currently there is a problem if we want to have WGLMakie installed along with DemoCards.

WGLMakie depends upon JSServe depends upon WebSockets, depends upon HTTP < 1
But Pluto depends upon HTTP > 1

See https://github.com/SimonDanisch/JSServe.jl/issues/131

**Comment by frankier** [comment]
@Dsantra92

**Comment by Dsantra92** [comment]
It can be done, but having HTTP < 1 looks a bit unreasonable to me. Can you confirm this the issue with Makie.jl with WGLMakie as backend?

**Comment by Dsantra92** [comment]
Looks like JSSserve.jl supports HTTP 0.8 and 0.9 only. But according to https://github.com/SimonDanisch/JSServe.jl/issues/131 next version of WebSockets will use 1.0+. So let's just wait till then? I don't think there will be any major updates in julia and markdown formats for now. So you can pin DemoCards.jl version until the release of WebSockets.jl.

**Comment by frankier** [comment]
Okay. Seems reasonable. Thanks!

**Comment by frankier** [comment]
I still think this would be a nice idea. I guess most people will not use the Pluto support, but as it is now, these projects get all of Pluto pulled in as dependencies into their docs. Note that currently Literate.jl does not have very many dependencies, and notably doesn't pull in any Jupyter stuff, it just generates the format as JSON. Adding Pluto as a dependency for all uses of this package could significantly increase TTFD (time to first doc).

**Comment by t-bltg** [comment]
This is a problem too for https://github.com/JuliaPlots/PlotDocs.jl.

**Comment by Dsantra92** [comment]
Hi, what is the current problem with PlotDocs.jl? Time to first plot?

**Comment by t-bltg** [comment]
Compat, can't update to latest `DemoCards`.

**Comment by Dsantra92** [comment]
Looks like more of a WebSockets.jl issue here. Track here https://github.com/JuliaWeb/WebSockets.jl/issues/181

**Comment by Dsantra92** [comment]
While I do recognize the time to first plot a good viable reason, I think moving a library to optional because another library release is taking time to release the next version is a bit of a hassle. Let's wait for a week and see how then plan on how the next release goes!

**Comment by frankier** [comment]
This could continue to be a compatibility problem later on as different parts of the ecosystem continue to be developed at different paces. It is not obvious why DemoCards.jl needs to depend upon Pluto if you are not using this feature.

**Comment by t-bltg** [comment]
What is @johnnychen94's opinion on this matter ?

**Comment by johnnychen94** [comment]
There are two issues to solve here:

- HTTP 1.0 compatibility. This should be fixed in other packages (e.g., https://github.com/JuliaWeb/WebSockets.jl/pull/182). It seems that WebSockets is approaching HTTP > 1.0 compatibility.
- the `using DemoCards` time. I agree that probably not all users need it, and it would be a good trade-off to introduce Requires.jl to load it conditionally. But I'm not sure how much code changes are involved here.

I do see people having the need to remove Pluto dependency completely from the current Project.toml. One way is to:

- revert the pluto-releated changes, tag a new v0.4.12 release
- tag a v0.5.0 release for Pluto-related features -- this is probably a large feature that requires a new breaking change.

and keep v0.4.x until the compatibility issue is solved.

**Comment by t-bltg** [comment]
It is unclear to me why https://github.com/JuliaDocs/DemoCards.jl/pull/121 needs to pull-in `Pluto` and `PlutoStaticHTML`.

Maybe @Dsantra92 could clarify.
Instead of adding `using Pluto`, one should use `import Pluto: ...` so that is immediate to see which components are effectively used.

I mean trivial helpers such as [`is_pluto_notebook`](https://github.com/fonsp/Pluto.jl/blob/9b4ca83da24b49d15e8192a70a4d8a985c554e37/src/notebook/path%20helpers.jl#L138) could easily be duplicated here ...

**Comment by hustf** [comment]
WebSockets.jl now has a new version, requiring Julia 1.8.2+ and HTTP 1.1.0 to 1.5. Hopefully, one plug is unstuck.

**Comment by Dsantra92** [comment]
I think it is better to make the dependency optional for the time being. Pluto and PlutoStaticHTML are not maintained in sync, resulting in bugs more often than anyone would like. Thanks, @t-bltg and @frankier for the suggestion.
